App/Models/MatchViewModel.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App.Models
{
    public class MatchViewModel
    {
        public Match match { get; set; }
        public IEnumerable<Entry> entries { get; set; }
    }
}

App/Controllers/MatchController.cs
using App.Models;
using BLL;
using Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App.Controllers
{
    public class MatchController : Controller
    {
        NBNBEntities db = new NBNBEntities();
        MatchManager matchManager = new MatchManager();

        // GET: Match
        public ActionResult Index(int? page, string searchString)
        {
            var match = matchManager. GetMatches();

            if (!String.IsNullOrEmpty(searchString))
            {
                match = match.Where(s => s.MName.Contains(searchString));
            }

            //第几页  
            int pageNumber = page ?? 1;
            //每页显示多少条  
            int pageSize = 24;
            //通过ToPagedList扩展方法进行分页  
            IPagedList<Match> pagedList = match.ToPagedList(pageNumber, pageSize);
            //将分页处理后的列表传给View  
            return View(pagedList);           
        }

        public ActionResult Publish()
        {
            if (Session["UserID"] != null)
            {
                ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName");

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Publish(Match match)
        {
            if (Session["UserID"] != null)
            {
                if (ModelState.IsValid)
                {
                    match.UserID = Convert.ToInt32(Session["UserID"].ToString());
                    match.MTime = System.DateTime.Now;
                    db.Match.Add(match);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }

                return View(match);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Add(Entry entry ,int? id)
        {
            int UserID = Convert.ToInt32(Session["UserID"].ToString());
            var entried = db.Entry.Where(o => o.UserID == UserID).Where(o => o.MID == id).FirstOrDefault();

            if (entried != null)
            {
                return Content("<script>;alert('您已经参加此赛事！');history.go(-1)</script>");
            }

            int currentEntryCount = db.Entry.Where(o => o.MID == id).Count();
            Match match = db.Match.Find(id);

            if (currentEntryCount >= match.MNum)
            {
                return Content("<script>;alert('抱歉！参赛人数已满！');history.go(-1)</script>");
            }

            db.Entry.Add(new Entry
            {
                UserID = Convert.ToInt32(Session["UserID"].ToString()),
                MID = id,
                ETime = DateTime.Now
            });
            db.SaveChanges();

            return Content("<script>;alert('参赛成功！');history.go(-1)</script>");
        }

        public ActionResult EntryDetails(int id)
        {
            var _match = db.Match.SingleOrDefault(x => x.MID == id);
            var _entries = db.Entry.Where(x => x.MID == id);
            var vm = new MatchViewModel
            {
                match = _match,
                entries = _entries
            };

            return View(vm);
        }        
    }
}

App/Views/Match/EntryDetails.cshtml
@using Models
@model  App.Models.MatchViewModel

@{
    ViewBag.Title = "NBNB-赛事详情";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="container">
    <div class="match-info">
        <h2 class="text-center">赛事详情</h2>
        <p><span class="glyphicon glyphicon-list-alt"> 赛事名称：@Model.match.MName</span></p>
        <p><span class="glyphicon glyphicon-map-marker"> 比赛地点：@Model.match.MAdder</span></p>
        <p><span class="glyphicon glyphicon-time"> 比赛时间：@Model.match.MAddtime</span></p>
        <p><span class="glyphicon glyphicon-star-empty"> 参赛人数：@Model.entries.Count()</span></p>
        <p><span class="glyphicon glyphicon-user"> 参赛用户：</span></p>
        <div class="row">
            @foreach (Entry e in Model.entries)
            {
                <div class="joinuser col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <div class="joinuserimg"><img class=" img-circle" src="@e.Users.UserAvatar" /></div>
                    <span>@e.Users.UserName</span>
                </div>
            }
        </div>
    </div>
</div>.

App/Views/Match/Index.cshtml
@model PagedList.IPagedList<Models.Match>
@using PagedList.Mvc;

@{
    ViewBag.Title = "NBNB-赛事列表";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="container">
    <h2 class="text-center" style="position: relative;">
        篮球约战
        <a href="/Match/Publish" style="position: absolute;right: 6px;">
            <span class="glyphicon glyphicon-plus" title="发布赛事" style="font-size: 20px;"></span>
        </a>
    </h2>
    
    <div class="row">

        @foreach (var m in Model)
        {
        <div class="bs col-lg-3 col-md-3 col-sm-4 col-xs-6">
            <a href="@Url.Action("EntryDetails","Match", new { id =m.MID})">
                <div class="match-list">
                    <img src="~/Images/logoo.png" />
                    <div>赛事名称：<span>@m.MName</span></div>
                    <div>发布时间：<span>@m.MTime</span></div>
                    <div>比赛地点：<span>@m.MAdder</span></div>
                    <div>参赛人数：<span>@m.MNum</span></div>
                    <div>比赛时间：<span>@m.MAddtime</span></div>
                    <div class="text-center">
                        @if (Session["UserName"] != null)
                        {

                            @Html.ActionLink("参赛", "Add", "Match", new { id = m.MID }, new { @class = "btn btn-success"});
                        }
                        else
                        {
                            @Html.ActionLink("参赛", "Index", "Login", new { @class = "btn btn-success" });
                        }
                    </div>
                </div>
            </a>
        </div>
        }
    </div>

    <div class="page">
        每页 @Model.PageSize 条记录，共 @Model.PageCount 页，当前第 @Model.PageNumber 页
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
</div>

App/Views/Match/Publish.cshtml
@model Models.Match
@{
    ViewBag.Title = "NBNB-发布赛事";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="container">
    <div style="position: relative;height: 600px;">
        <div class="loginbox" style="padding: 10px;top: 50px;z-index: 0;">
            <h2 class="text-center">发布赛事</h2>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div style="margin: 30px 0;">
                    <span>赛事名称：</span>
                    @Html.EditorFor(model => model.MName)
                    @Html.ValidationMessageFor(model => model.MName)
                </div>
                <div style="margin: 30px 0;">
                    <span>参赛人数：</span>
                    @Html.EditorFor(model => model.MNum)
                    @Html.ValidationMessageFor(model => model.MNum)
                </div>
                <div style="margin: 30px 0;">
                    <span>比赛地点：</span>
                    @Html.EditorFor(model => model.MAdder)
                    @Html.ValidationMessageFor(model => model.MAdder)
                </div>
                <div style="margin: 30px 0;">
                    <span>比赛时间：</span>
                    @Html.EditorFor(model => model.MAddtime)
                    @Html.ValidationMessageFor(model => model.MAddtime)
                </div>
                <div class="text-center" style="margin: 30px 0;">
                    <input type="submit" value="发布" class="btn btn-success" />
                </div>
            }
        </div>
    </div>
</div>