App/Models/UserViewModel.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App.Models
{
    public class UserViewModel
    {
        public News News { get; set; }

        public IEnumerable<News> News1 { get; set; }

        public IEnumerable<NewsComment> NewsComment1 { get; set; }

        public Users user { get;set; }

        public IEnumerable<Entry> entries { get; set; }

        public IEnumerable<Posts> posts { get; set; }

        public IEnumerable<Match> match { get; set; }
    }

    public class NewsCommentViewModel
    {
        public NewsComment NComment { get; set; }

        public string NTitle { get; set; }
    }

    public class MatchViewModel1
    {
        public Entry ety { get; set; }
        public string MName { get; set; }
    }
}

App/Controllers/LoginController.cs
using Models;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App.Controllers
{
    public class LoginController : Controller
    {
        NBNBEntities db = new NBNBEntities();

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LogOff()
        {
            Session["UserID"] = null;
            Session["UserName"] = null;
            Session["UserAvatar"] = null;

            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(Users user, string returnUrl)
        {
            string ValidateCode = Request["txtverifcode"];

            if (ValidateCode != Session["ValidateCode"].ToString())
            {
                return Content("<script>;alert('验证码错误！');history.go(-1)</script>");
            }

            try
            {
                var users = db.Users.Where(o => o.UserName == user.UserName).Where(o => o.UserPassword == user.UserPassword).FirstOrDefault();
                if (users != null)
                {
                    //以下代码将权限保存到Session
                    HttpContext.Session["UserID"] = users.UserID;
                    HttpContext.Session["UserName"] = users.UserName;
                    HttpContext.Session["UserAvatar"] = users.UserAvatar;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return Content("<script>;alert('该账号不存在!');history.go(-1)</script>");
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
    }
}

App/Controllers/UserController.cs
using App.Models;
using BLL;
using Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace App.Controllers
{
    public class UserController : Controller
    {
        NBNBEntities db = new NBNBEntities();

        // GET: User
        public ActionResult Index()
        {
            int UserID = Convert.ToInt32(Session["UserID"].ToString());
            Users users = db.Users.Find(UserID);

            return View(users);
        }

        public ActionResult MyComment()
        {
            int UserID = Convert.ToInt32(Session["UserID"].ToString());
            var ncomments = db.NewsComment.Where(p => p.UserID == UserID).ToList();
            IList<NewsCommentViewModel> vmlist = new List<NewsCommentViewModel>();

            foreach (var item in ncomments)
            {
                string ntitle = db.News.Where(x => x.NID == item.NID).Select(x => x.NTitle).SingleOrDefault();
                vmlist.Add(new NewsCommentViewModel
                {
                    NComment = item,
                    NTitle = ntitle
                });
            }

            return View(vmlist);
        }

        public ActionResult DelectComment(int id)
        {
            NewsComment newsComment = db.NewsComment.Find(id);

            int UserID = Convert.ToInt32(Session["UserID"].ToString());
            var delc = db.NewsComment.Where(c => c.NCID == id).Where(c => c.UserID == UserID).SingleOrDefault();
            db.NewsComment.Remove(newsComment);
            db.SaveChanges();

            return RedirectToAction("MyComment");
        }

        public ActionResult MyMatch()
        {
            int UserID = Convert.ToInt32(Session["UserID"].ToString());
            var entry = db.Entry.Where(p => p.UserID == UserID).ToList();
            IList<MatchViewModel1> mlist = new List<MatchViewModel1>();

            foreach (var item in entry)
            {
                string mname = db.Match.Where(m => m.MID == item.MID).Select(m => m.MName).SingleOrDefault();
                mlist.Add(new MatchViewModel1
                {
                    ety = item,
                    MName = mname,
                });
            }

            return View(mlist);
        }

        public ActionResult MyPosts(int? id)
        {
            int UserID = Convert.ToInt32(Session["UserID"].ToString());
            Posts posts = db.Posts.Find(id);
            var p = db.Posts.Where(m => m.UserID == UserID).OrderByDescending(n => n.PTime).ToList();
            var index = new Models.UserViewModel
            {
                posts = p,
            };

            return View(index);
        }

        public ActionResult Delect(int id)
        {
            Posts posts = db.Posts.Find(id);
            int UserID = Convert.ToInt32(Session["UserID"].ToString());
            var del = db.Posts.Where(p => p.PID == id).Where(p => p.UserID == UserID).SingleOrDefault();
            db.Posts.Remove(posts);
            db.SaveChanges();

            return RedirectToAction("MyPosts");
        }

        public ActionResult Changeinfo()
        {
            if (Session["UserID"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(Session["UserID"]);

            if (users == null)
            {
                return HttpNotFound();
            }

            return View(users);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Changeinfo([Bind(Include = "UserName,UserTpl,UserSex,UserEmail,UserAge,UserHeight,UserWeight")] Users users)
        {
            if (TryUpdateModel(users, new string[] { "UserName", "UserEmail", "UserTpl", "UserSex", "UserAge", "UserHeight", "UserWeight" }))
            {
                if (ModelState.IsValid)
                {
                    UpdateModel(users);
                    db.SaveChanges();
                }
            }
            else ModelState.AddModelError("", "更新模型数据失败");
            return View("Index", users);
        }
    }
}

App/Views/User/Changeinfo.cshtml
@model Models.Users
@{
    ViewBag.Title = "NBNB-修改信息";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="container">
    <div class="user-center">
        <div class="row">
            <div class="user-all col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <div class="user-photo">
                    <img src="@Html.DisplayFor(model => model.UserAvatar)" />
                </div>
                <ul class="user-all-ul">
                    <li class="myinfo"><a href="/User/Index">我的信息</a></li>
                    <li class="mygame"><a href="/User/MyMatch">我的约战</a></li>
                    <li class="myposts"><a href="/User/MyPosts">我的帖子</a></li>
                    <li class="mycomment"><a href="/User/MyComment">我的评论</a></li>
                    <li class="myorder"><a href="/ShoppingCart/Index">我的订单</a></li>
                    <li class="changeinfo user-active"><a href="/User/Changeinfo">修改信息</a></li>
                    <li class="logout"><a href="@Url.Action("LogOff", "Login")">注销登录</a></li>
                </ul>
            </div>
            <div class="user-body col-lg-9 col-md-9 col-sm-8 col-xs-6">
                <h4><span>修改信息</span></h4>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UserID)
                    <table class="table table-hover">
                        <tr>
                            <td>
                                用户名
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                        <tr>
                            <td>
                                用户密码
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                        <tr>
                            <td>
                                手机号
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserTpl, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserTpl, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                        <tr>
                            <td>
                                性别
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserSex, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserSex, "", new { @class = "text-danger" })
                            </td>
                        </tr>                       
                        <tr>
                            <td>
                                邮箱
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                        <tr>
                            <td>
                                年龄
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserAge, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserAge, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                        <tr>
                            <td>
                                身高
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserHeight, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserHeight, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                        <tr>
                            <td>
                                体重
                            </td>
                            <td>
                                @Html.EditorFor(model => model.UserWeight, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserWeight, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="text-center">
                                <input type="submit" value="保存" class="btn btn-success" />
                            </td>
                        </tr>
                    </table>
                }
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</div>

App/Views/User/Index.cshtml
@model Models.Users
@{
    ViewBag.Title = "NBNB-个人中心";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="container">
    <div class="user-center">
        <div class="row">
            <div class="user-all col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <div class="user-photo">
                    <img src="@Html.DisplayFor(model => model.UserAvatar)" />
                </div>
                <ul class="user-all-ul">
                    <li class="myinfo user-active"><a href="/User/Index">我的信息</a></li>
                    <li class="mygame"><a href="/User/MyMatch">我的约战</a></li>
                    <li class="myposts"><a href="/User/MyPosts">我的帖子</a></li>
                    <li class="mycomment"><a href="/User/MyComment">我的评论</a></li>
                    <li class="myorder"><a href="/ShoppingCart/Index">我的订单</a></li>
                    <li class="changeinfo"><a href="/User/Changeinfo">修改信息</a></li>
                    <li class="logout"><a href="@Url.Action("LogOff", "Login")">注销登录</a></li>                    
                </ul>
            </div>
            <div class="user-body col-lg-9 col-md-9 col-sm-8 col-xs-6">
                <h4><span>用户信息</span></h4>
                <ul>
                    <li><span>用户名：</span>@Model.UserName</li>

                    <li><span>性别：</span>@Html.DisplayFor(model => model.UserSex)</li>

                    <li><span>电话：</span>@Html.DisplayFor(model => model.UserTpl)</li>

                    <li><span>年龄：</span>@Html.DisplayFor(model => model.UserAge)</li>

                    <li><span>email：</span>@Html.DisplayFor(model => model.UserEmail)</li>

                    <li><span>身高：</span>@Html.DisplayFor(model => model.UserHeight)</li>

                    <li><span>体重：</span>@Html.DisplayFor(model => model.UserWeight)</li>
                </ul>
            </div>
        </div>
    </div>
</div>

App/Views/User/MyComment.cshtml
@model List<App.Models.NewsCommentViewModel>
@{
    ViewBag.Title = "MyComment";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="container">
    <div class="user-center">
        <div class="row">
            <div class="user-all col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <div class="user-photo">
                    <img src="@Session["UserAvatar"]" />
                </div>
                <ul class="user-all-ul">
                    <li class="myinfo"><a href="/User/Index">我的信息</a></li>
                    <li class="mygame"><a href="/User/MyMatch">我的约战</a></li>
                    <li class="myposts"><a href="/User/MyPosts">我的帖子</a></li>
                    <li class="mycomment user-active"><a href="/User/MyComment">我的评论</a></li>
                    <li class="myorder"><a href="/ShoppingCart/Index">我的订单</a></li>
                    <li class="changeinfo"><a href="/User/Changeinfo">修改信息</a></li>
                    <li class="logout"><a href="@Url.Action("LogOff", "Login")">注销登录</a></li>
                </ul>
            </div>
            <div class="user-body col-lg-9 col-md-9 col-sm-8 col-xs-6">
                <h4><span>我的评论</span></h4>
                <table class="table table-hover">
                    <tr>
                        <th>
                            评论文章
                        </th>
                        <th>
                            评论内容
                        </th>
                        <th>
                            评论时间
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(item.NTitle.ToString(), "Details", "News", new { id = item.NComment.NID }, new { })
                            </td>
                            <td>
                                @Html.Raw(item.NComment.NCContent)
                            </td>
                            <td>
                                @item.NComment.NCTime
                            </td>  
                            <td>
                                @Html.ActionLink("删除", "DelectComment", "User", new { id = item.NComment.NCID }, null)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>   
</div>

App/Views/User/MyMatch.cshtml
@model List<App.Models.MatchViewModel1>
@{
    ViewBag.Title = "NBNB-我的赛事";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


<div class="container">
    <div class="user-center">
        <div class="row">
            <div class="user-all col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <div class="user-photo">
                    <img src="@Session["UserAvatar"]" />
                </div>
                <ul class="user-all-ul">
                    <li class="myinfo"><a href="/User/Index">我的信息</a></li>
                    <li class="mygame user-active"><a href="/User/MyMatch">我的约战</a></li>
                    <li class="myposts"><a href="/User/MyPosts">我的帖子</a></li>
                    <li class="mycomment"><a href="/User/MyComment">我的评论</a></li>
                    <li class="myorder"><a href="/ShoppingCart/Index">我的订单</a></li>
                    <li class="changeinfo"><a href="/User/Changeinfo">修改信息</a></li>
                    <li class="logout"><a href="@Url.Action("LogOff", "Login")">注销登录</a></li>
                </ul>
            </div>
            <div class="user-body col-lg-9 col-md-9 col-sm-8 col-xs-6">
                <h4><span>我的约战</span></h4>
                <table class="table table-hover">
                    <tr>
                        <th>赛事名称</th>
                        <th>参赛时间</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MName</td>    
                            <td>@item.ety.ETime</td>
                        </tr>
                    }
                </table>
                
            </div>
        </div>
    </div>
    
</div>

App/Views/User/MyPosts.cshtml
@using Models
@model App.Models.UserViewModel

@{
    ViewBag.Title = "NBNB-我的帖子";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="container">
    <div class="user-center">
        <div class="row">
            <div class="user-all col-lg-3 col-md-3 col-sm-4 col-xs-6">
                <div class="user-photo">
                    <img src="@Session["UserAvatar"]" />
                </div>
                <ul class="user-all-ul">
                    <li class="myinfo"><a href="/User/Index">我的信息</a></li>
                    <li class="mygame"><a href="/User/MyMatch">我的约战</a></li>
                    <li class="myposts user-active"><a href="/User/MyPosts">我的帖子</a></li>
                    <li class="mycomment"><a href="/User/MyComment">我的评论</a></li>
                    <li class="myorder"><a href="/ShoppingCart/Index">我的订单</a></li>
                    <li class="changeinfo"><a href="/User/Changeinfo">修改信息</a></li>
                    <li class="logout"><a href="@Url.Action("LogOff", "Login")">注销登录</a></li>
                </ul>
            </div>
            <div class="user-body col-lg-9 col-md-9 col-sm-8 col-xs-6">
                <h4><span>我的帖子</span></h4>
                <table class="table table-hover">
                    <tr>
                        <th>帖子名</th>
                        <th>发帖时间</th>
                        <th></th>
                    </tr>

                    @foreach (Posts n in Model.posts)
                    {
                        <tr>
                            <td>
                                <a href="@Url.Action("Details","Posts", new { id =n.PID})">@n.PTitle</a>
                            </td>
                            <td>
                                @String.Format("{0:yyyy-MM-dd HH:mm}", n.PTime)
                            </td>
                            <td>
                                @Html.ActionLink("删除", "Delect", "User", new { id = n.PID }, null)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
    
</div>